/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.fblumgarcia.ui;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import com.fblumgarcia.model.DataBase;
import com.fblumgarcia.model.Validations;

/**
     * <h1>UIMPcreate</h1>
     * <p> Formato visual para acceder a agregar productos
     * @author fblumgarcia
     * https://github.com/fblumgarcia
     * 
     */
public class UIMPcreate extends javax.swing.JPanel {
    FileInputStream image;
    /**
     * Creates new form UIMPcreate
     */
    public UIMPcreate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        categoryTB = new javax.swing.JComboBox<>();
        nameTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        priceTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        quantityTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        descriptionTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        selectImg = new javax.swing.JButton();

        categoryTB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "TELEVISOR", "CELULAR", "COMPUTADOR" }));

        nameTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setText("NOMBRE");

        priceTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        priceTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                priceTFKeyTyped(evt);
            }
        });

        jLabel3.setText("PRECIO");

        quantityTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantityTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                quantityTFKeyTyped(evt);
            }
        });

        jLabel4.setText("CANTIDAD");

        descriptionTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setText("DESCRIPCIÓN");

        register.setText("Registrar");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        selectImg.setText("Seleccionar Imágen");
        selectImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectImgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(93, 93, 93)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(quantityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(priceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 226, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(selectImg, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(311, 311, 311))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(categoryTB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(78, 78, 78)
                        .addComponent(descriptionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(categoryTB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(selectImg, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(descriptionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selectImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectImgActionPerformed
        JFileChooser imgChooser=new JFileChooser();//Se inicializa el filechooser
        imgChooser.setCurrentDirectory(new java.io.File("C:\\Users\\fblum\\Documents\\Proyectos\\StoreFBG\\src\\images"));
        imgChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);//Selecciona sólo los archivos
        FileNameExtensionFilter imgFilter=new FileNameExtensionFilter("JPEG file", "jpg", "jpeg");//Sólo se puede seleccionar este tipo de archivo
        imgChooser.setFileFilter(imgFilter);
        int result=imgChooser.showOpenDialog(this);//Para saber que botón selecciona
        if(result!=JFileChooser.CANCEL_OPTION){
            File img=imgChooser.getSelectedFile();//Devuelve el objeto seleccionado
            try {
                image=new FileInputStream(String.valueOf(img));//Convierte la ruta de la imagen en fileinputstream
            } catch (FileNotFoundException ex) {
                Logger.getLogger(UIMPcreate.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_selectImgActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        DataBase dataBase=new DataBase();
        int price=-1;int quantity=-1;boolean isCreated=false;      
        String category=(categoryTB.getSelectedItem().toString().toUpperCase());String name=category+" "+nameTF.getText().toUpperCase();String description=descriptionTF.getText().toUpperCase();
        if(quantityTF.getText().equals("")||priceTF.getText().equals("")||name.equals("")||category.equals("")||description.equals("SELECCIONE")){
            JOptionPane.showMessageDialog(null,"Ingrese todos los datos");
        }else{
            price=Integer.valueOf(priceTF.getText());quantity=Integer.valueOf(quantityTF.getText());
            isCreated=dataBase.CreateProduct(name, price, quantity, image, description);//Se envía con este procedimiento
            if(isCreated==true){//Si se guarda en la DB
                JOptionPane.showMessageDialog(null,"Se ha creado el producto");
            }else{
                JOptionPane.showMessageDialog(null,"No se ha creado el producto");
            }
        }
    }//GEN-LAST:event_registerActionPerformed

    private void quantityTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityTFKeyTyped
        char caracter = evt.getKeyChar();
        Validations val=new Validations();
      // Verificar si la tecla pulsada no es un digito
        if(true==val.OnlyNumbers(caracter)){
         evt.consume();  // ignorar el evento de teclado
        }   
    }//GEN-LAST:event_quantityTFKeyTyped

    private void priceTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceTFKeyTyped
        char caracter = evt.getKeyChar();//Captura la tecla presionada
        Validations val=new Validations();
        // Verificar si la tecla pulsada no es un digito
        if(true==val.OnlyNumbers(caracter)){
         evt.consume();  // ignorar el evento de teclado
        }
    }//GEN-LAST:event_priceTFKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> categoryTB;
    private javax.swing.JTextField descriptionTF;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nameTF;
    private javax.swing.JTextField priceTF;
    private javax.swing.JTextField quantityTF;
    private javax.swing.JButton register;
    private javax.swing.JButton selectImg;
    // End of variables declaration//GEN-END:variables
}
