/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.fblumgarcia.ui;

/**
     * <h1>UIModifyProduct</h1>
     * <p> Formato visual para acceder al modificador del producto para crearlo o editar o borrar
     * @author fblumgarcia
     * https://github.com/fblumgarcia
     * 
     */
public class UISModifyProduct extends javax.swing.JPanel {
    UIMPcreate create;UIMPmodify modify;
    /**
     * Creates new form UISModifyProduct
     */
    public UISModifyProduct() {
        initComponents();
        create=new UIMPcreate();
        modify=new UIMPmodify();
        create.setBounds(0, 21, 1000, 579);add(create);create.setVisible(false);
        modify.setBounds(0, 21, 1000, 579);add(modify);modify.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createProd = new javax.swing.JButton();
        modifyProd = new javax.swing.JButton();

        setForeground(new java.awt.Color(255, 153, 255));

        createProd.setText("Crear");
        createProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProdActionPerformed(evt);
            }
        });

        modifyProd.setText("Modificar");
        modifyProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(createProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modifyProd)
                .addGap(0, 841, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createProd)
                    .addComponent(modifyProd))
                .addContainerGap(557, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void modifyProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyProdActionPerformed
        modify.setVisible(true);
        create.setVisible(false);
        revalidate();
        repaint();
    }//GEN-LAST:event_modifyProdActionPerformed

    private void createProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProdActionPerformed
        modify.setVisible(false);
        create.setVisible(true);
        revalidate();
        repaint();
    }//GEN-LAST:event_createProdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createProd;
    private javax.swing.JButton modifyProd;
    // End of variables declaration//GEN-END:variables
}
