package com.fblumgarcia.ui;

import java.util.ArrayList;

/**
     * <h1>UIStore</h1>
     * <p> Formato visual para acceder al inicio de la tienda
     * @author fblumgarcia
     * https://github.com/fblumgarcia
     * 
     */
public class UIStore extends javax.swing.JFrame {
    
    UISProducts products;UISShop shop;UISProfile profile;UISModifyProduct modifyProduct;
    private ArrayList user=new ArrayList();
    /**
     * Creates new form UIStore
     */
    public UIStore(String name,String email,String userType) {
        initComponents();
        products=new UISProducts();//LLama al panel productos
        shop=new UISShop();
        profile=new UISProfile();
        modifyProduct=new UISModifyProduct();
        products.setBounds(0, 21, 1000, 579);//Define posición y dimensiones
        add(products);products.setVisible(false);//Lo añade y oculta
        shop.setBounds(0, 21, 1000, 579);add(shop);shop.setVisible(false);
        profile.setBounds(0, 21, 1000, 579);add(profile);profile.setVisible(false);
        modifyProduct.setBounds(0, 21, 1000, 579);add(modifyProduct);modifyProduct.setVisible(false);
        if(userType.equals("CLIENTE")){//Si el usuario es cliente oculta la opción Users y modificar Productos
            menModifyProducts.setVisible(false);
        }
        lblWelc.setText("Bienvenid@ "+name+" a STOREFBG");//Da el mensaje de bienvenida
        //falta el logo
        user.add(name);user.add(email);
    }
    

    private ArrayList getUser() {//Array para obtener el user de la BD
        return user;
    }
    
    public UIStore() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JPanel();
        lblWelc = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        menProducts = new javax.swing.JMenu();
        menShop = new javax.swing.JMenu();
        menProfile = new javax.swing.JMenu();
        menModifyProducts = new javax.swing.JMenu();
        logout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("STORE FBG");

        logo.setBackground(new java.awt.Color(204, 204, 204));
        logo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        logo.setForeground(new java.awt.Color(0, 0, 51));

        lblWelc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblWelc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout logoLayout = new javax.swing.GroupLayout(logo);
        logo.setLayout(logoLayout);
        logoLayout.setHorizontalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(lblWelc, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        logoLayout.setVerticalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblWelc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(518, Short.MAX_VALUE))
        );

        jMenuBar2.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar2.setForeground(new java.awt.Color(255, 102, 51));

        menProducts.setBackground(new java.awt.Color(204, 204, 204));
        menProducts.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        menProducts.setForeground(new java.awt.Color(0, 0, 51));
        menProducts.setText("PRODUCTOS");
        menProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menProductsMouseClicked(evt);
            }
        });
        jMenuBar2.add(menProducts);

        menShop.setBackground(new java.awt.Color(204, 204, 204));
        menShop.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        menShop.setForeground(new java.awt.Color(0, 0, 51));
        menShop.setText("CARRITO DE COMPRA");
        menShop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menShop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menShopMouseClicked(evt);
            }
        });
        jMenuBar2.add(menShop);

        menProfile.setBackground(new java.awt.Color(204, 204, 204));
        menProfile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        menProfile.setForeground(new java.awt.Color(0, 0, 51));
        menProfile.setText("MI PERFIL");
        menProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menProfileMouseClicked(evt);
            }
        });
        jMenuBar2.add(menProfile);

        menModifyProducts.setBackground(new java.awt.Color(204, 204, 204));
        menModifyProducts.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        menModifyProducts.setForeground(new java.awt.Color(0, 0, 51));
        menModifyProducts.setText("MODIFICAR PRODUCTOS");
        menModifyProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menModifyProductsMouseClicked(evt);
            }
        });
        jMenuBar2.add(menModifyProducts);

        logout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        logout.setText("CERRAR SESIÓN");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jMenuBar2.add(logout);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menProductsMouseClicked
        products.setVisible(true);
        shop.setVisible(false);
        logo.setVisible(false);
        profile.setVisible(false);
        modifyProduct.setVisible(false);
        revalidate();
        repaint();
    }//GEN-LAST:event_menProductsMouseClicked

    private void menShopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menShopMouseClicked
        products.setVisible(false);
        shop.setVisible(true);
        shop.ShowTable(products.getProductsBuy());shop.ShowUser(user);
        logo.setVisible(false);
        profile.setVisible(false);
        modifyProduct.setVisible(false);
        /*revalidate();
        repaint();*/
    }//GEN-LAST:event_menShopMouseClicked

    private void menProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menProfileMouseClicked
        products.setVisible(false);
        shop.setVisible(false);
        logo.setVisible(false);
        profile.setVisible(true);profile.ShowUser(user);
        modifyProduct.setVisible(false);
        revalidate();
        repaint();
    }//GEN-LAST:event_menProfileMouseClicked

    private void menModifyProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menModifyProductsMouseClicked
        products.setVisible(false);
        shop.setVisible(false);
        logo.setVisible(false);
        profile.setVisible(false);
        modifyProduct.setVisible(true);
        revalidate();
        repaint();
    }//GEN-LAST:event_menModifyProductsMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        UILogin login=new UILogin();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIStore().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JLabel lblWelc;
    private javax.swing.JPanel logo;
    private javax.swing.JMenu logout;
    private javax.swing.JMenu menModifyProducts;
    private javax.swing.JMenu menProducts;
    private javax.swing.JMenu menProfile;
    private javax.swing.JMenu menShop;
    // End of variables declaration//GEN-END:variables
}
